//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documate.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppDbCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppDbCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Documate.Resources.Models.AppDbCreate", typeof(AppDbCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking the application database version..
        /// </summary>
        internal static string CheckAppDbVersion {
            get {
                return ResourceManager.GetString("CheckAppDbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation/updating of the database (tables) is complete. (Version: {0}).
        /// </summary>
        internal static string CreateAndOrUpdateTableReady {
            get {
                return ResourceManager.GetString("CreateAndOrUpdateTableReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create table {0}. (Version {1})..
        /// </summary>
        internal static string CreateTableFailed {
            get {
                return ResourceManager.GetString("CreateTableFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application database is already present..
        /// </summary>
        internal static string DbFileAlreadyExists {
            get {
                return ResourceManager.GetString("DbFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty database file has been created..
        /// </summary>
        internal static string EmptyDbFileCreated {
            get {
                return ResourceManager.GetString("EmptyDbFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection to the database..
        /// </summary>
        internal static string ErrorDbConnection {
            get {
                return ResourceManager.GetString("ErrorDbConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application database has not been created..
        /// </summary>
        internal static string FailedToCreateDbFile {
            get {
                return ResourceManager.GetString("FailedToCreateDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert data into table {0}..
        /// </summary>
        internal static string FailedToInsertDataIntoTabel {
            get {
                return ResourceManager.GetString("FailedToInsertDataIntoTabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change version in table {0}. (Version {1} )..
        /// </summary>
        internal static string FailedToUpdateTable {
            get {
                return ResourceManager.GetString("FailedToUpdateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta version request failed. (Version {1})..
        /// </summary>
        internal static string RequestMetaVersionFailed {
            get {
                return ResourceManager.GetString("RequestMetaVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving database version..
        /// </summary>
        internal static string RetrieveDbVersionError {
            get {
                return ResourceManager.GetString("RetrieveDbVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving database version. return version: -1.
        /// </summary>
        internal static string RetrieveDbVersionErrorReturnDefault {
            get {
                return ResourceManager.GetString("RetrieveDbVersionErrorReturnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setting done: auto_vacuum = incremental..
        /// </summary>
        internal static string SetAutoVacuum {
            get {
                return ResourceManager.GetString("SetAutoVacuum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the database setting &apos;auto_vacuum = incremental&apos; failed..
        /// </summary>
        internal static string SetAutoVacuumFailed {
            get {
                return ResourceManager.GetString("SetAutoVacuumFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setting done: pragma USER_VERSION = {0}..
        /// </summary>
        internal static string SetDbUserVersionIsReady {
            get {
                return ResourceManager.GetString("SetDbUserVersionIsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database setting done: journal_mode = wal..
        /// </summary>
        internal static string SetJournalMode {
            get {
                return ResourceManager.GetString("SetJournalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the database setting &apos;journal_mode = wal&apos; failed..
        /// </summary>
        internal static string SetJournalModeFailed {
            get {
                return ResourceManager.GetString("SetJournalModeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table {0} has been created. (Version: {1})..
        /// </summary>
        internal static string TableIsCreated {
            get {
                return ResourceManager.GetString("TableIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table {0} has been updated..
        /// </summary>
        internal static string TableIsUpdated {
            get {
                return ResourceManager.GetString("TableIsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table {0} has been updated. (Version: {1})..
        /// </summary>
        internal static string TableIsUpdatedWithVersion {
            get {
                return ResourceManager.GetString("TableIsUpdatedWithVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error when creating an empty database file..
        /// </summary>
        internal static string UnexpectedErrorCreDbFile {
            get {
                return ResourceManager.GetString("UnexpectedErrorCreDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting up the database &apos;USER_VERSION&apos; failed..
        /// </summary>
        internal static string UpdateDbUserVersionFailed {
            get {
                return ResourceManager.GetString("UpdateDbUserVersionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enter the database version number in table {0}. (Version {1})..
        /// </summary>
        internal static string UpdateVersionNumberFailed {
            get {
                return ResourceManager.GetString("UpdateVersionNumberFailed", resourceCulture);
            }
        }
    }
}
