//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documate.Resources.Presenters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainPresenter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPresenter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Documate.Resources.Presenters.MainPresenter", typeof(MainPresenter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new database file....
        /// </summary>
        internal static string CreateNewDbFile {
            get {
                return ResourceManager.GetString("CreateNewDbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English activated.
        /// </summary>
        internal static string ENIsActivated {
            get {
                return ResourceManager.GetString("ENIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been closed..
        /// </summary>
        internal static string FileIsClosed {
            get {
                return ResourceManager.GetString("FileIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been created..
        /// </summary>
        internal static string FileIsCreated {
            get {
                return ResourceManager.GetString("FileIsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch activated.
        /// </summary>
        internal static string NLIsActivated {
            get {
                return ResourceManager.GetString("NLIsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Documentation database file....
        /// </summary>
        internal static string OpenDocumateFile {
            get {
                return ResourceManager.GetString("OpenDocumateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location....
        /// </summary>
        internal static string SelectFileLocation {
            get {
                return ResourceManager.GetString("SelectFileLocation", resourceCulture);
            }
        }
    }
}
